##################################################
# Program Workflow
#
# true if you want to use the config file to run the program
# or false if you want to interact with the program through the console
use_config_workflows: true
##################################################


# Step 1: Login
login:
  active: mis
  # Available options: mis, cookie
  mis:
    # Path to the webdriver (leave empty if you want to use the default path)
    webdriver_path: ""
    browser: chrome
  cookie:
    # Must be provided if you choose Cookie login
    # How to get the cookie > https://github.com/ymzhang-cs/BJTU-Homework-Tracker/blob/master/FOR_NEWERS.md
    JSESSIONID: ""
  cp:
    student_id: "23114514"
    password: "pass:Bjtu@23114514"
    # password: "hash:0f932b38dd9ac1a09b4c38febf01fab0"
    # leave it empty for default password
    # password: ""

# Step 3: Select the homework
select:
  active: true
  conditions:
    course_positive_keyword: []  # leave [] if you want to select all courses
    course_negative_keyword: []    # leave [] if you want to select all homework
    finish_status: unfinished      # all / finished / unfinished
    ignore_expired_n_days: 15       # ignore the homework that expired for n days+
    ignore_unexpired_n_days: 90        # ignore the homework that unexpired for n days+



# Step 4: Process method

# How to process the homework html code
# plain_text: convert to plain text (show in console and/or save to file)
# html: render to html (show in browser)
process_method: plain_text


# Step 5: Save record
# Save to file or not
save_record:
  # Save record to file or not
  active: true
  # Record file folder
  save_record_folder: "./search_history"
  # Record file name
  # 1. Use timestamp (format configurable)
  # 2. Custom name (may cover the previous record)
  save_record_name_type: 1
  timestamp_format: "%Y-%m-%d %H-%M-%S"
  custom_name: "search_record"

